"""
Example taken from https://paulbourke.net/fractals/lsys/.
"""

from l_system.base import Lsystem
from l_system.rendering.turtle import TurtleConfiguration


class DenseFans(Lsystem):
    """Figure 1.10: Examples of curves generated by edge-rewriting L-systems: (b) the Sierpinski gasket."""

    axiom = "F"
    productions = {"F": "F[+FF][-FF]F[-F][+F]F"}
    recursions = 3


DEFAULT_TURTLE_CONFIG = TurtleConfiguration(angle=35)
